### ISSUE TITLE
Producer is not alive

### ISSUE THREAD

**Issue by drozzy** [NFIBrokerage/volley#4]
Hi, I'm just starting with volley and my elixir is a bit rusty.  I'm trying to create an aggregate root, for which I think in-order subscription is the right approach (to prevent invalid commands etc).

Why am I getting this error? I thought that the `Volley` lib is supposed to start the producer named `DatasetProducer` for me?
```elixir
 iex -S mix 
Erlang/OTP 25 [RELEASE CANDIDATE 1] [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]


19:52:11.960 [error] GenStage consumer MyApp.Dataset was not able to subscribe to the process DatasetProducer because that process is not alive

 
19:52:11.969 [notice] Application my_app exited: MyApp.Application.start(:normal, []) returned an error: shutdown: failed to start child: MyApp.Dataset
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
 
19:52:11.972 [notice] Application volley exited: :stopped
 
19:52:11.972 [notice] Application gen_stage exited: :stopped
 
19:52:11.972 [notice] Application jason exited: :stopped

19:52:11.972 [notice] Application spear exited: :stopped

19:52:11.972 [notice] Application connection exited: :stopped
 
19:52:11.972 [notice] Application event_store_db_gpb_protobufs exited: :stopped

19:52:11.972 [notice] Application gpb exited: :stopped
 
19:52:11.972 [notice] Application mint exited: :stopped
 
19:52:11.972 [notice] Application hpax exited: :stopped
** (Mix) Could not start application my_app: MyApp.Application.start(:normal, []) returned an error: shutdown: failed to start child: MyApp.Dataset
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started

```

Here is my complete source:
```elixir
## application.ex
defmodule MyApp.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    in_order_subscription_settings = [
      name: DatasetProducer,
      connection: MyApp.EventStoreDbClient,
      stream_name: "Dataset"
    ]

    children = [
      MyApp.EventStoreDbClient,
      MyApp.Dataset,
      {Volley.InOrderSubscription, in_order_subscription_settings}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: MyApp.Supervisor]
    Supervisor.start_link(children, opts)
  end
end


### my_app.ex
defmodule MyApp do
  def create_mock_dataset do
    event = Spear.Event.new("DatasetCreated", %{"id" => 2_208_061_522, "name" => "Mock Dataset"})

    [event] |> Spear.append(MyApp.EventStoreDbClient, "Dataset")
  end
end


## dataset.ex

defmodule MyApp.Dataset do
  use GenStage

  def start_link(_) do
    GenStage.start_link(__MODULE__, :ok)
  end

  @impl GenStage
  def init(:ok) do
    {:consumer, :ok, subscribe_to: [DatasetProducer]}
  end

  @impl GenStage
  def handle_events(events, _from, state) do
    IO.inspect(events, label: "events")

    {:noreply, [], state}
  end
end


## event_store_db_client.ex
defmodule MyApp.EventStoreDbClient do
  use Spear.Client,
    otp_app: :my_app
end

## mix.exs
defmodule MyApp.MixProject do
  use Mix.Project

  def project do
    [
      app: :my_app,
      version: "0.1.0",
      elixir: "~> 1.13",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger],
      mod: {MyApp.Application, []}
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      {:spear, "~> 1.0"},
      {:jason, "~> 1.0"},
      {:volley, "~> 1.0"}
    ]
  end
end

```

**Comment by the-mikedavis** [comment]
I think you may need to reorder your application children so that the InOrderSubscription producer is started before the consumer:

```elixir
children = [
  MyApp.EventStoreDbClient,
  {Volley.InOrderSubscription, in_order_subscription_settings},
  MyApp.Dataset
]
```

Does that boot up successfully?

**Comment by drozzy** [comment]
Ok, that seems to have done something. I'm getting this error now (I'm sure I messed something up):

```
iex(1)> 
20:13:48.945 [error] GenServer DatasetProducer terminating
** (FunctionClauseError) no function clause matching in Volley.InOrderSubscription.do_function/1
    (volley 1.0.0) lib/volley/in_order_subscription.ex:537: Volley.InOrderSubscription.do_function(nil)
    (volley 1.0.0) lib/volley/in_order_subscription.ex:467: Volley.InOrderSubscription.read_stream/2
    (volley 1.0.0) lib/volley/in_order_subscription.ex:393: Volley.InOrderSubscription.handle_demand/2
    (gen_stage 1.1.2) lib/gen_stage.ex:2117: GenStage.noreply_callback/3
    (stdlib 4.0) gen_server.erl:702: :gen_server.try_dispatch/4
    (stdlib 4.0) gen_server.erl:778: :gen_server.handle_msg/6
    (stdlib 4.0) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :subscribe
State: %Volley.InOrderSubscription{connection: MyApp.EventStoreDbClient, demand: 1, producing?: false, read_opts: [], restore_stream_position!: nil, self: DatasetProducer, stream_name: "Dataset", subscribe_after: 0, subscribe_on_init?: {Volley, :yes, []}, subscription: nil}
 
20:13:48.953 [notice] GenStage consumer #PID<0.240.0> is stopping after receiving cancel from producer #PID<0.239.0> with reason: {:function_clause,
 [
   {Volley.InOrderSubscription, :do_function, [nil],
    [file: 'lib/volley/in_order_subscription.ex', line: 537]},
   {Volley.InOrderSubscription, :read_stream, 2,
    [file: 'lib/volley/in_order_subscription.ex', line: 467]},
   {Volley.InOrderSubscription, :handle_demand, 2,
    [file: 'lib/volley/in_order_subscription.ex', line: 393]},
   {GenStage, :noreply_callback, 3, [file: 'lib/gen_stage.ex', line: 2117]},
   {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 702]},
   {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 778]},
   {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}
 ]}

 
20:13:48.954 [info]  Volley.InOrderSubscription (DatasetProducer) subscribing to 'Dataset'
 
20:13:48.954 [error] GenServer DatasetProducer terminating
** (FunctionClauseError) no function clause matching in Volley.InOrderSubscription.do_function/1
    (volley 1.0.0) lib/volley/in_order_subscription.ex:537: Volley.InOrderSubscription.do_function(nil)
    (volley 1.0.0) lib/volley/in_order_subscription.ex:467: Volley.InOrderSubscription.read_stream/2
    (volley 1.0.0) lib/volley/in_order_subscription.ex:393: Volley.InOrderSubscription.handle_demand/2
    (gen_stage 1.1.2) lib/gen_stage.ex:2117: GenStage.noreply_callback/3
    (stdlib 4.0) gen_server.erl:702: :gen_server.try_dispatch/4
    (stdlib 4.0) gen_server.erl:778: :gen_server.handle_msg/6
    (stdlib 4.0) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :subscribe
State: %Volley.InOrderSubscription{connection: MyApp.EventStoreDbClient, demand: 0, producing?: false, read_opts: [], restore_stream_position!: nil, self: DatasetProducer, stream_name: "Dataset", subscribe_after: 0, subscribe_on_init?: {Volley, :yes, []}, subscription: nil}
 
20:13:48.954 [error] GenServer #PID<0.240.0> terminating
** (FunctionClauseError) no function clause matching in Volley.InOrderSubscription.do_function/1
    (volley 1.0.0) lib/volley/in_order_subscription.ex:537: Volley.InOrderSubscription.do_function(nil)
    (volley 1.0.0) lib/volley/in_order_subscription.ex:467: Volley.InOrderSubscription.read_stream/2
    (volley 1.0.0) lib/volley/in_order_subscription.ex:393: Volley.InOrderSubscription.handle_demand/2
    (gen_stage 1.1.2) lib/gen_stage.ex:2117: GenStage.noreply_callback/3
    (stdlib 4.0) gen_server.erl:702: :gen_server.try_dispatch/4
    (stdlib 4.0) gen_server.erl:778: :gen_server.handle_msg/6
    (stdlib 4.0) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.239407594.4188012545.71159>, :process, #PID<0.239.0>, {:function_clause, [{Volley.InOrderSubscription, :do_function, [nil], [file: 'lib/volley/in_order_subscription.ex', line: 537]}, {Volley.InOrderSubscription, :read_stream, 2, [file: 'lib/volley/in_order_subscription.ex', line: 467]}, {Volley.InOrderSubscription, :handle_demand, 2, [file: 'lib/volley/in_order_subscription.ex', line: 393]}, {GenStage, :noreply_callback, 3, [file: 'lib/gen_stage.ex', line: 2117]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 702]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 778]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
State: :ok
 
20:13:48.955 [info]  Volley.InOrderSubscription (DatasetProducer) subscribing to 'Dataset'
 
20:13:48.955 [error] GenServer DatasetProducer terminating
** (FunctionClauseError) no function clause matching in Volley.InOrderSubscription.do_function/1
    (volley 1.0.0) lib/volley/in_order_subscription.ex:537: Volley.InOrderSubscription.do_function(nil)
    (volley 1.0.0) lib/volley/in_order_subscription.ex:467: Volley.InOrderSubscription.read_stream/2
    (volley 1.0.0) lib/volley/in_order_subscription.ex:393: Volley.InOrderSubscription.handle_demand/2
    (gen_stage 1.1.2) lib/gen_stage.ex:2117: GenStage.noreply_callback/3
    (stdlib 4.0) gen_server.erl:702: :gen_server.try_dispatch/4
    (stdlib 4.0) gen_server.erl:778: :gen_server.handle_msg/6
    (stdlib 4.0) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :subscribe
State: %Volley.InOrderSubscription{connection: MyApp.EventStoreDbClient, demand: 1, producing?: false, read_opts: [], restore_stream_position!: nil, self: DatasetProducer, stream_name: "Dataset", subscribe_after: 0, subscribe_on_init?: {Volley, :yes, []}, subscription: nil}
 
20:13:48.955 [notice] Application my_app exited: shutdown

```

**Comment by the-mikedavis** [comment]
I think you'll need a `restore_stream_position!` option in `in_order_subscription_settings` which is a zero-arity function that gives the event number of the last event handled by the consumer or `:start` if the consumer hasn't handled any events yet

**Comment by drozzy** [comment]
Ok this works:
```
stream_name: "Dataset",
restore_stream_position!: fn -> :start end
```

**Comment by drozzy** [comment]
Should I use the same handler as a genserver for handling commands?
How do you deal with the case of aggregate consistency and event store events?
Is there something like Commanded interface here: https://hexdocs.pm/commanded/0.14.0/aggregate-roots.html ?

For example, let's say I'm implementing an aggregate root to control the duplicate creation of  datasets. Can't this thing happen if I simply implement my commands in `GenStage`?

1. Receive call to create new Dataset with ID 1. My `GenStage` verifies that no such dataset exists yet. Send Event `DatasetCreated(1)` to EventStore Reply `:ok`.
2. Handle event "DatasetCreated" setting state to `{"1" -> "Dataset 1"}`
3. Receive call to create new Dataset with ID 2. My `GenStage` verifies that no such dataset exists yet. Send Event `DatasetCreated(2)` to EventStore. Reply `:ok`.
4. Receive call to create new Dataset with ID 2. My `GenStage` verifies that no such dataset exists yet. Send Event `DatasetCreated(2)` to EventStore. Reply `:ok`.
5. Error - two events of type `DatasetCreated(2)` were now issued. So duplicate id exists.

P.S: Is there a slack/forum channel were I can join? I don't want to create useless issues here. Thanks!

**Comment by the-mikedavis** [comment]
The simplest way to prevent a consistency problem there would be to have a single process in charge of handling all commands - that way you couldn't handle two conflicting commands at once. It's a very consistent approach at the cost of throughput because you can't handle unrelated commands - commands targeting different entities - in parallel. If you don't have throughput problems though then it's a good approach and easy to reason about.

In order to handle commands with a high throughput while keeping consistency, you should partition incoming commands to a set of GenStage consumers by their entity IDs. You can set that up more easily with Broadway which has a `partition_by` option that takes a partitioning function. For this approach you need to have the producers of commands generate new entity IDs rather than the aggregate itself. You can have command producers generate a fresh UUIDv4 for each CreateDataset command or maybe a UUIDv5 or `:erlang.phash2/2` some input data if you want a deterministic ID.

For potentially maximum throughput though, there's a third option that doesn't need any collaboration between consumers (or IDs on CreateDataset messages I suppose). You can use EventStoreDB's expectation system to handle commands with optimistic concurrency. When you read the event history for an entity, you hold on to the last event in the stream and when you go append new events created by handling the command, you _expect_ that last event.

```elixir
def handle_command(command) do
  stream_name = "DataSet-#{command.id}"
  event_history = MySpearClient.stream!(stream_name)
  expectation =
    case Enum.take(event_history, -1) do
      [last_event] -> last_event
      [] -> :empty
    end
  state = Enum.reduce(event_history, %State{}, &fold_history_into_state/2)
  {:ok, new_events} = decide_new_events_for_command_and_state(command, state)

  case MySpearClient.append(new_events, stream_name, expect: expectation) do
    :ok ->
      Logger.info("successfully handled")

    {:error, %Spear.ExpectationViolation{}} ->
      Logger.warn("""
      Another command was handled while handling this command.
      This command should be retried
      """)

    {:error, reason} ->
      Logger.error("""
      Failed to append events!
      Probably for something network related: #{inspect(reason)}
      """)
  end
end
```

If some other consumer of commands has handled CreateDataset for ID=2 at the same time as another, the slower of the two consumers will fail to append events. This probably maximizes throughput but you have to deal with that failure, for example by retrying failed commands.

All of these only need Spear though and are agnostic of how commands are delivered. Afaik, NFIBrokerage only uses Volley for writing process managers and read model projections. For delivering commands to consumers, I think it's considered an anti-pattern to use the EventStoreDB as a message broker; you can use a message broker or even just HTTP calls for simplicity.

> Is there a slack/forum channel were I can join? I don't want to create useless issues here. Thanks!

I'm on the DDD-CQRS-ES, Elixir, Erlang and RabbitMQ Slacks plus the Elixir and Erlang forums if you have questions especially about Spear or things built with it implementation-wise. I'm not super knowledgeable about DDD/CQRS/ES so it may be easier to get questions to answers like that from the DDD-CQRS-ES Slack or the `#commanded` channel in the Elixir Slack. I'm most active on github though. I can go ahead and enable github discussions on the spear repo but we'll need an active NFIBrokerage member to enable them here too

**Comment by drozzy** [comment]
Thank you for the answers. The third one looks like what I want. It seems like a general pattern for any aggregate root to follow.

> Afaik, NFIBrokerage only uses Volley for writing process managers and read model projections

So do you use sql for storing your entities/aggregates? 

Could you clarify what you mean by "For delivering commands to consumers, I think it's considered an anti-pattern to use the EventStoreDB as a message broker"?

**Comment by drozzy** [comment]
One thing i don't understand is:
```
event_history = MySpearClient.stream!(stream_name)
```
This seems to replay history every time a command is handled?

**Comment by the-mikedavis** [comment]
> So do you use sql for storing your entities/aggregates?

We use EventStoreDB for storing entities/aggregates. An example aggregate might be a Phoenix application that receives commands as POSTs and `GenServer.call/3`s a GenServer that keeps the consistency guarantees. The implementation for that GenServer can look just like the code-snippet above (although it wouldn't need the expectation part because the GenServer forces consistency). It's a little limited throughput-wise and you do end up recomputing the `event_history` for every handled command but in practice it works well and is very fast for entities with event history streams containing fewer than ~100 events.

Volley is meant for long-running consumption of EventStoreDB streams. I suppose you could use Volley to read the event history for an entity when making a decision but it's simpler to use `Spear.stream!/3` for that use-case.

> I think it's considered an anti-pattern to use the EventStoreDB as a message broker

It certainly _can_ work to put your commands in EventStoreDB and have aggregates consume commands from them. You could use Volley for this but you would want to handle one command at a time or partition commands by entity ID. Once a command is handled though there isn't much reason for it to remain in the EventStoreDB. With EventStoreDB, persistence of messages is the default which is good for events. Message brokers are typically geared toward treating messages as semi-transient data to be discarded at the end of handling, which is good for commands. Performance-wise, EventStoreDB is very good at reads and okay at writes; message-brokers tend to have roughly equal performance for publishing and consuming. I'm not sure how well EventStoreDB deals with high event churn (commands being published, consumed, and then deleted with high throughput) internally. It may not be a use-case EventStoreDB was built for.

> This seems to replay history every time a command is handled?

Yep! If your event streams are short (<5k events) and each event is reasonably small (~100KB), this ends up not being a practical problem. There are optimizations you can make if it becomes a problem though: you can cache event histories or create snapshots for entity streams.

**Comment by drozzy** [comment]
> The simplest way to prevent a consistency problem there would be to have a single process in charge of handling all commands 

Actually, I really like this simple approach. Do you have an example of code for this that would also work for all types of aggregates? I assume it would be something like what you provided before but simplified?
Here is my attempt:

```elixir
def handle_command(command) do
  stream_name = "#{command.aggregate_name}-#{command.id}"
  event_history = MySpearClient.stream!(stream_name)
 
  state = Enum.reduce(event_history, %State{}, &fold_history_into_state/2)
  case decide_new_events_for_command_and_state(command, state) do
     {:ok, new_events} -> pass
     {:error, reason} -> {reply, {:error, reason}, ...}
  end 

 MySpearClient.append(new_events, stream_name)
  {reply, :ok} 
  end
end
```

**Comment by the-mikedavis** [comment]
Yep that looks perfect 👍

For the GenServer part of it, you don't even need to care about state really:

```elixir
defmodule MyCommandHandler do
  use GenServer

  def handle_command(command, timeout \\ 5_000) do
    GenServer.call(__MODULE__, {:handle_command, command}, timeout)
  end

  @doc false
  def start_link(arg) do
    GenServer.start_link(__MODULE__, arg, name: __MODULE__)
  end

  @impl GenServer
  def init(_init_arg) do
    {:ok, nil}
  end

  @impl GenServer
  def handle_call({:handle_command, command}, _from, gen_server_state) do
    stream_name = "#{command.aggregate_name}-#{command.id}"

    event_history = MySpearClient.stream!(stream_name)
    entity_state = Enum.reduce(event_history, %State{}, &fold_history_into_state/2)

    case decide_new_events_for_command_and_state(command, entity_state) do
      {:ok, new_events} ->
        :ok = MySpearClient.append(new_events, stream_name)
        {:reply, :ok, gen_server_state}
       
      {:error, reason} ->
        {:reply, {:error, reason}, gen_server_state}
    end
  end
end
```

Or you could use the GenServer state to track event histories to make things faster at the cost of memory.
